export const OPEN_JOB_DIALOG = 'OPEN_JOB_DIALOG';
export const CLOSE_JOB_DIALOG = 'CLOSE_JOB_DIALOG';
export const OPEN_CREATE_CANDIDATE_DIALOG = 'OPEN_CREATE_CANDIDATE_DIALOG';
export const CLOSE_CREATE_CANDIDATE_DIALOG = 'CLOSE_CREATE_CANDIDATE_DIALOG';
export const OPEN_CREATE_JOB_DIALOG = 'OPEN_CREATE_JOB_DIALOG';
export const CLOSE_CREATE_JOB_DIALOG = 'CLOSE_CREATE_JOB_DIALOG';
